Repository bolti95/jidiBackend, pull requests merged in 2020-11, with the labels that each got.

#15 checkout router added
  lib/connection.js
  routes/checkoutRouter.js
Labels: help wanted

#17 updated router file
  routes/router.js
Labels: help wanted

#18 basket router added
  routes/basketRouter.js
Labels: help wanted

#21 adding untracked files and index
  .gitignore
  index.js
  lib/connection.js
  package-lock.json
  package.json
  routes/checkoutRouter.js
  routes/router.js
Labels: help wanted

#40 more variable changes
  controllers/connectionController.js
Labels: priority

#42 adding users to database
  index.js
  lib/connection.js
  routes/signupRouter.js
Labels: enhancement

#41 Signup two
  index.js
  lib/connection.js
  package-lock.json
  package.json
  routes/checkoutRouter.js
  routes/customerOrderRouter.js
  routes/signupRouter.js
  routes/stockedProductsRouter.js
Labels: help wanted

#44 Working
  index.js
  lib/connection.js
  models/sessionModel.js
  models/userModel.js
  routes/loginRouter.js
  routes/signupRouter.js
Labels: enhancement
